from wx import ID_HIGHEST
ID_BASE				= ID_HIGHEST + 1
ID_SWITCH_PANE		= ID_BASE + 1
ID_IPP_TOGGLE		= ID_BASE + 2
ID_IPP_TEST_TOOGLE	= ID_BASE + 3
ID_SPIDER_FACTIVA	= ID_BASE + 4
ID_SPIDER_ZHIHU		= ID_BASE + 5
ID_SPIDER_WEIBO		= ID_BASE + 6
ID_SPIDER_START		= ID_BASE + 7
ID_SPIDER_PAUSE		= ID_BASE + 8
ID_SPIDER_STOP		= ID_BASE + 9